frr version 8.0
frr defaults traditional
hostname _wil-4
no ipv6 forwarding
!
interface lo
 ip address 1.1.1.4/32
 ip ospf area 0
!
interface eth0
 ip address 10.1.1.10/30
 ip ospf area 0
!
router ospf
 ospf router-id 1.1.1.4
 network 1.1.1.4/32 area 0
 network 10.1.1.0/24 area 0
!
router bgp 1
 bgp router-id 1.1.1.4
 no bgp default ipv4-unicast
 bgp log-neighbor-changes
 neighbor 1.1.1.1 remote-as 1
 neighbor 1.1.1.1 update-source lo
 !
 address-family l2vpn evpn
  neighbor 1.1.1.1 activate
  advertise-all-vni
 exit-address-family
!
